FROM --platform=$BUILDPLATFORM mcr.microsoft.com/dotnet/sdk:9.0-alpine AS base

ARG TARGETPLATFORM
ARG TARGETOS
ARG TARGETARCH
ARG TARGETVARIANT
ARG BUILDPLATFORM
ARG BUILDOS
ARG BUILDARCH
ARG BUILDVARIANT

COPY *.sln .
COPY Selector/*.csproj ./Selector/
COPY Selector.AppleMusic/*.csproj ./Selector.AppleMusic/
COPY Selector.Spotify/*.csproj ./Selector.Spotify/
COPY Selector.LastFm/*.csproj ./Selector.LastFm/
COPY Selector.Cache/*.csproj ./Selector.Cache/
COPY Selector.Data/*.csproj ./Selector.Data/
COPY Selector.Event/*.csproj ./Selector.Event/
COPY Selector.Model/*.csproj ./Selector.Model/
COPY Selector.CLI/*.csproj ./Selector.CLI/
COPY Selector.Tests/*.csproj ./Selector.Tests/
RUN dotnet restore ./Selector.CLI/Selector.CLI.csproj -a $TARGETARCH

COPY . ./

FROM base as publish
RUN dotnet publish Selector.CLI/Selector.CLI.csproj -c Release -a $TARGETARCH -o /app

FROM mcr.microsoft.com/dotnet/aspnet:9.0-alpine
WORKDIR /app
COPY --from=publish /app ./
ENV DOTNET_EnableDiagnostics=0

USER app

ENTRYPOINT ["dotnet", "Selector.CLI.dll"]

