version: "3.9"
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile.Web
    ports:
      - "8080:80"
  cli:
    build: 
      context: .
      dockerfile: Dockerfile.CLI
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
  database:
    image: postgres
    ports:
      - "5432:5432"
