FROM --platform=$BUILDPLATFORM node:22-alpine as frontend

ARG TARGETPLATFORM
ARG TARGETOS
ARG TARGETARCH
ARG TARGETVARIANT
ARG BUILDPLATFORM
ARG BUILDOS
ARG BUILDARCH
ARG BUILDVARIANT

COPY ./Selector.Web/package.json /Selector.Web/
COPY ./Selector.Web/package-lock.json /Selector.Web/
WORKDIR /Selector.Web
RUN npm ci
COPY ./Selector.Web ./
RUN npm run build

FROM --platform=$BUILDPLATFORM mcr.microsoft.com/dotnet/sdk:9.0-alpine AS base

ARG TARGETPLATFORM
ARG TARGETOS
ARG TARGETARCH
ARG TARGETVARIANT
ARG BUILDPLATFORM
ARG BUILDOS
ARG BUILDARCH
ARG BUILDVARIANT

COPY *.sln .
COPY Selector/*.csproj ./Selector/
COPY Selector.AppleMusic/*.csproj ./Selector.AppleMusic/
COPY Selector.Spotify/*.csproj ./Selector.Spotify/
COPY Selector.LastFm/*.csproj ./Selector.LastFm/
COPY Selector.Cache/*.csproj ./Selector.Cache/
COPY Selector.Data/*.csproj ./Selector.Data/
COPY Selector.Event/*.csproj ./Selector.Event/
COPY Selector.Model/*.csproj ./Selector.Model/
COPY Selector.Web/*.csproj ./Selector.Web/
COPY Selector.SignalR/*.csproj ./Selector.SignalR/
COPY Selector.Tests/*.csproj ./Selector.Tests/
RUN dotnet restore ./Selector.Web/Selector.Web.csproj -a $TARGETARCH

COPY . ./

FROM base as publish
COPY --from=frontend /Selector.Web/wwwroot Selector.Web/wwwroot/
RUN dotnet publish Selector.Web/Selector.Web.csproj -c Release -a $TARGETARCH -o /app

FROM mcr.microsoft.com/dotnet/aspnet:9.0-alpine
EXPOSE 80
WORKDIR /app
COPY --from=publish /app ./
ENV DOTNET_EnableDiagnostics=0

USER app

ENTRYPOINT ["dotnet", "Selector.Web.dll"]
