FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build

COPY *.sln .
COPY Selector/*.csproj ./Selector/
COPY Selector.Cache/*.csproj ./Selector.Cache/
COPY Selector.Event/*.csproj ./Selector.Event/
COPY Selector.Model/*.csproj ./Selector.Model/
COPY Selector.CLI/*.csproj ./Selector.CLI/
RUN dotnet restore ./Selector.CLI/Selector.CLI.csproj

COPY . ./
RUN dotnet publish Selector.CLI/Selector.CLI.csproj -c Release -o /app --no-restore

FROM mcr.microsoft.com/dotnet/runtime:6.0
WORKDIR /app
COPY --from=build /app ./
ENV DOTNET_EnableDiagnostics=0
ENTRYPOINT ["dotnet", "Selector.CLI.dll"]

