name: ci

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    name: Build & Unit Test
    strategy:
      fail-fast: false
      matrix:
        dotnet-version: [ '8.0.x' ]

    steps:
      - uses: actions/checkout@v4
        with: 
          github-server-url: https://gitea.sheep-ghoul.ts.net
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3.0.3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Install Dependencies
        run: dotnet restore Selector.Core.sln
      - name: Build
        run: dotnet build --configuration Debug --no-restore Selector.Core.sln
      - name: Test
        run: dotnet test --no-restore --verbosity normal Selector.Core.sln

  build-Docker:

    runs-on: ubuntu-latest
    name: Build Containers
    needs: [build, build-Js] # for ignoring bad builds
    if: gitea.event_name == 'push' && (gitea.ref == 'refs/heads/master' || startsWith(gitea.ref, 'refs/tags/'))

    steps:
      - uses: actions/checkout@v4
        with: 
          github-server-url: https://gitea.sheep-ghoul.ts.net

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: gitea.sheep-ghoul.ts.net
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build CLI Container
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: gitea.sheep-ghoul.ts.net/sarsoo/selector-cli:latest
          file: Dockerfile.CLI
          context: .

      - name: Build Web Container
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: gitea.sheep-ghoul.ts.net/sarsoo/selector-web:latest
          file: Dockerfile.Web
          context: .

  build-Js:

    runs-on: ubuntu-latest
    name: Build Frontend
    strategy:
      fail-fast: false
      matrix:
        node: [21]
    
    steps:
      - uses: actions/checkout@v4
        with: 
          github-server-url: https://gitea.sheep-ghoul.ts.net
      
      - name: Install Node ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Install Node Packages
        working-directory: ./Selector.Web
        run: npm ci
      
      - name: Compile Front-end
        working-directory: ./Selector.Web
        run: npm run build --if-present
