name: ci

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        dotnet-version: [ '5.0.x' ]

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Install Dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Test
        run: dotnet test --no-restore --verbosity normal

  build-Js:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node: [16]
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Install Node ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Install Node Packages
        working-directory: ./Selector.Web/Frontend
        run: npm ci
      
      - name: Compile Front-end
        working-directory: ./Selector.Web/Frontend
        run: npm run build --if-present
